id: P003305
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG11868
  title: སྤྲུལ་སྐུ་ཀརྨ་གླིང་པའི་གཏེར་བྱོན་བཛྲ་གུ་རུའི་ཕན་ཡོན་དང་འབྲུ་འགྲེལ།
  author: ''
  volumes:
    928a3f31894241309989e7d9da9d640d:
      image_group_id: I1KG11873
      title: ''
      volume_number: 1
      total_pages: 20
      base_file: v001.txt
